# Generated by Django 5.0.6 on 2024-06-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_next_rename_book_book_read_alter_vote_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_read',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
    ]
